{% set name = "bytefield" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bytefield-{{ version }}.tar.gz
  sha256: eb5f8c8d51de54d8764041531521e072b4e6208acd3504f1f2260c0d6377599e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - bytefield
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/donadigo/bytefield
  summary: Parse binary data using declarative field layout and native Python properties
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
